language: node_js
branches:
  only:
    - master
    - staging
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_script:
  - |
    if [ ! -z $CC_TEST_REPORTER_ID ]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi
script:
  - npm run test:prod && npm run build
after_script:
  - |
    if [ ! -z $CC_TEST_REPORTER_ID ]; then
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    fi
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run changelog
  - npm run semantic-release
  - git stash && git checkout -B develop && git stash pop && git add .